apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
  labels:
    app: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
        - name: argocd-demo-app
          image: vaibhav/argocd-demo-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-app-service
spec:
  selector:
    app: argocd-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
